# Generated by Django 2.0.7 on 2019-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190113_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='door_number',
            field=models.IntegerField(default=1),
        ),
    ]
