# Generated by Django 2.0.7 on 2019-01-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0005_userbinmap'),
        ('users', '0004_auto_20190120_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postcode_ref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.PostcodeTBL'),
        ),
    ]
