# Generated by Django 2.1.4 on 2019-01-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('bin_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilRegistration',
            fields=[
                ('council_id', models.AutoField(primary_key=True, serialize=False)),
                ('council_name', models.CharField(max_length=60)),
                ('council_code', models.CharField(max_length=60)),
                ('council_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='binschedule',
            name='council_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.CouncilRegistration'),
        ),
    ]
