# Generated by Django 2.1.4 on 2019-01-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binschedule',
            name='council_id',
        ),
    ]
