# Generated by Django 2.1.4 on 2019-01-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeTBL',
            fields=[
                ('postcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=10)),
                ('council_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.CouncilRegistration')),
            ],
        ),
    ]
