# Generated by Django 2.1.4 on 2019-01-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0002_postcodetbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeGrouping',
            fields=[
                ('grouping_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('area', models.CharField(max_length=60)),
                ('postcode_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.PostcodeTBL')),
            ],
        ),
    ]
