# Generated by Django 2.0.7 on 2019-01-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0003_postcodegrouping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinScheduleMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binschedule_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.BinSchedule')),
                ('postcodegrouping_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.PostcodeGrouping')),
            ],
        ),
    ]
