# Generated by Django 2.1.4 on 2019-01-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0003_binschedule_council_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binschedule',
            name='council_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.CouncilRegistration'),
        ),
    ]
