# Generated by Django 2.0.7 on 2019-01-13 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduleapi', '0004_binschedulemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBinMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.BinType')),
                ('userbin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
