# Generated by Django 2.1.4 on 2019-01-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0004_auto_20190104_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinType',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('bin_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='binschedule',
            name='bin_type',
        ),
        migrations.AddField(
            model_name='binschedule',
            name='bin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleapi.BinType'),
        ),
    ]
