# Generated by Django 2.0.7 on 2019-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapi', '0005_userbinmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binschedulemapping',
            name='postcodegrouping_id',
        ),
        migrations.AddField(
            model_name='binschedulemapping',
            name='postcodegrouping_id',
            field=models.ManyToManyField(to='scheduleapi.PostcodeGrouping'),
        ),
    ]
